// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeQz57SN9Sm3oGC7TBonc6A19mV2Orn0E',
    appId: '1:313530131305:web:18f476edf05cabfffa93f8',
    messagingSenderId: '313530131305',
    projectId: 'task-manager-1763e',
    authDomain: 'task-manager-1763e.firebaseapp.com',
    storageBucket: 'task-manager-1763e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlIi_QGr0YolwIyKIOYBcJrBE7VZlNRto',
    appId: '1:313530131305:android:eddabb90633c0e82fa93f8',
    messagingSenderId: '313530131305',
    projectId: 'task-manager-1763e',
    storageBucket: 'task-manager-1763e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0dYTOJfPpikNHa9zmq3PZxKGG1n0n-UY',
    appId: '1:313530131305:ios:b5c1e6a2fae16d70fa93f8',
    messagingSenderId: '313530131305',
    projectId: 'task-manager-1763e',
    storageBucket: 'task-manager-1763e.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0dYTOJfPpikNHa9zmq3PZxKGG1n0n-UY',
    appId: '1:313530131305:ios:b5c1e6a2fae16d70fa93f8',
    messagingSenderId: '313530131305',
    projectId: 'task-manager-1763e',
    storageBucket: 'task-manager-1763e.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeQz57SN9Sm3oGC7TBonc6A19mV2Orn0E',
    appId: '1:313530131305:web:cf9d3157536bedc6fa93f8',
    messagingSenderId: '313530131305',
    projectId: 'task-manager-1763e',
    authDomain: 'task-manager-1763e.firebaseapp.com',
    storageBucket: 'task-manager-1763e.firebasestorage.app',
  );
}
