// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ey54PyHK2y1jv0SRp4fWdDOo2TefJt4',
    appId: '1:59089217990:web:a3d65ca679181cc8932ac7',
    messagingSenderId: '59089217990',
    projectId: 'task-manager-5ca23',
    authDomain: 'task-manager-5ca23.firebaseapp.com',
    storageBucket: 'task-manager-5ca23.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwxkr75sn_NZfYGglF1_DNrlvmMJCRunw',
    appId: '1:59089217990:android:ff45a8a1c68ab7b5932ac7',
    messagingSenderId: '59089217990',
    projectId: 'task-manager-5ca23',
    storageBucket: 'task-manager-5ca23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdTeFaIgH5J2N6GRLb3Ytdujw1KD833a4',
    appId: '1:59089217990:ios:a8e6ce97f6ac69c2932ac7',
    messagingSenderId: '59089217990',
    projectId: 'task-manager-5ca23',
    storageBucket: 'task-manager-5ca23.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdTeFaIgH5J2N6GRLb3Ytdujw1KD833a4',
    appId: '1:59089217990:ios:a8e6ce97f6ac69c2932ac7',
    messagingSenderId: '59089217990',
    projectId: 'task-manager-5ca23',
    storageBucket: 'task-manager-5ca23.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9ey54PyHK2y1jv0SRp4fWdDOo2TefJt4',
    appId: '1:59089217990:web:5f9448d585ccbc9a932ac7',
    messagingSenderId: '59089217990',
    projectId: 'task-manager-5ca23',
    authDomain: 'task-manager-5ca23.firebaseapp.com',
    storageBucket: 'task-manager-5ca23.firebasestorage.app',
  );
}
